# Use an official Node.js runtime as a parent image
FROM node:18

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install app dependencies
RUN npm install

# Copy the rest of your application code to the container
COPY . .

# Expose the port your Node.js app is running on
EXPOSE 3000

# Define the command to run your Node.js app
CMD ["npx", "ts-node", "server.ts"]
